#!/bin/sh
#usage:$0 c-source[.c]
#	wiringPi simple compile
#	[]:option

##a.c
#B_NAME=${1##*/}
##c
#EXTENSION=${1##*.}

#a
F_NAME=${1%.*}

#echo $0 $1 $2

cc $F_NAME".c" -o $F_NAME -lwiringPi -lpthread
#cc $F_NAME".c" -o $F_NAME -lwiringPi -static -lpthread
#cc $F_NAME".c" -o $F_NAME -lwiringPi -static
#cc $F_NAME".c" -o $F_NAME -lwiringPi
#cc $F_NAME".c" -o $F_NAME -l/usr/local/lib/libwiringPi.so.2.25
